config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_count

  private

  def update_count
    post.update(comments_count: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'

  after_save :update_count

  private

  def update_count
    post.update(likes_count: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, foreign_key: 'post_id'
  has_many :comments, foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :comments_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  recent_comments = ->(no) { comments.order(created_at: :desc).limit(no) }

  define_method :recent_comments, recent_comments

  after_save :update_count

  private

  def update_count
    author.update(posts_count: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id', through: :posts
  has_many :likes, foreign_key: 'author_id', through: :posts

  validates :name, presence: true
  validates :posts_count, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  recent_posts = ->(no) { posts.order(created_at: :desc).limit(no) }
  define_method :recent_posts, recent_posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  include Devise::Controllers::Helpers
  before_action :allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!, unless: -> { request.format.json? }

  protected

  def allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio email password current_password])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new; end

  def create
    @post = Post.find(params[:post_id])
    text = comment_params
    @comment = Comment.new(text:, post: @post, author: current_user)
    if @comment.save
      flash[:success] = 'Comment created successfully'
      redirect_to user_post_path(@post.author_id, @post.id)
    else
      flash[:alert] = "Comment couldn't be created"
      render 'new'
    end
  end

  private

  def comment_params
    params.require(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new(author: current_user, post: @post)
    if @like.save
      flash.now[:success] = 'You just liked this post...'
      redirect_to user_post_path(@like.author_id, @like.post_id)
    else
      flash[:alert] = 'Like unsuccessful...'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_user, only: %i[index show create]
  def new; end

  def index
    @posts = @user.posts.includes(:comments).where(author_id: @user.id).paginate(page: params[:page], per_page: 2)
    render 'index', locals: { user: @user, posts: @posts }
  end

  def show
    @post = @user.posts.includes(:comments).find(params[:id])
  end

  def create
    title = params[:title]
    text = params[:text]
    @post = Post.new(title:, text:, likes_count: 0, comments_count: 0, author: @user)
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_path(@post.author_id)
    else
      flash[:alert] = "Post couldn't be created"
      render 'new'
    end
  end

  private

  load_user = -> { @user = User.includes(:posts).find(params[:user_id]) }
  define_method :load_user, load_user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    render 'show', locals: { myuser: @user }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
  def show_comments(post)
    comments = Comment.where(post_id: post.id)
    if post.comments_count.nil?
      content_tag(:p, 'No Comments Yet!')
    else
      output = content_tag(:h3, '')
      comments.each do |comment|
        user = User.find(comment.author_id)
        comment_html = content_tag(:p, "#{user.name}: #{comment.text}")
        output += content_tag(:li, comment_html, class: 'comment-item')
      end
      output
    end
  end
end

app/views/comments/new.html.erb
<h2>Adding a comment</h2>

<%= form_with(model: @comment, url: user_post_comments_path, local: true, method: :post) do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text, rows: 6, cols: 35, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_comlist.html.erb
<% @posts.each do |post| %>
  <%= render partial: 'users/show', object: post, as: :post %>
  <div class="comment-container">
    <h3>Recent Comments</h3>
    <% comments = post.recent_comments(5) %>
    <% if comments.length.positive? then %>
      <%= render partial: 'posts/listcoms', collection: comments, as: :comment %>
    <% else %>
      <p>No Comments yet!</p>
    <% end %>
  </div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: url, local: true, method: :post) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, required: true %>
  </div>

  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text, rows: 6, cols: 35, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_listcoms.html.erb
<li>
    <% user = User.find(comment.author_id) %>
    <p><strong><%= user.name %></strong> : <%= comment.text %></p>
</li>

app/views/posts/index.html.erb
<h1><%= user.name %>'s Posts and Comments</h1>
<%= render partial: 'users/list', object: user, as: :user %>
<%= render partial: 'comlist', posts: @posts, object: user, as: :user %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>
<%= render partial: 'posts/form', locals: {post: @post, url: user_posts_path } %>

app/views/posts/show.html.erb
<div class="top-com">
    <h1>Post#<%= @post.id %> by <%= @user.name %></h1>
    <%= render partial: 'users/show', object: @post, as: :post %>
</div>
<div class="comment-container">
    <h3>Post Comments</h3>
    <%= show_comments(@post) %>
</div>
<div class="buttons">
    <%= button_to 'Add a Like', user_post_likes_path(@user.id, @post.id), method: :post %>
    <%= button_to 'Add a Comment', new_user_post_comment_path(@user.id, @post.id), method: :get %>
</div>

app/views/users/_list.html.erb
<li class="user-item">
    <img src="<%= user.photo %>" alt="<%= user.name %>">
    <%= puts user.posts_count %>
    <%= link_to user_path(user.id), class: "main-details" do %>
            <h2><%= user.name %></h2>
            <p class="item-no">Number of posts : <%= user.posts_count %></p>
    <% end %>
</li>

app/views/users/_show.html.erb
<%= link_to user_post_path(@user.id, post.id), class: 'com_nav' do %>
    <li class="post-item">
        <h3><%= post.title %></h3>
        <div class="inner-items">
            <p><%= post.text %></p>
            <p class="item-no">Comments: <%= post.comments_count %>, Likes: <%= post.likes_count %></p>
        </div>
    </li>
<% end %>

app/views/users/index.html.erb
<h1 class="header">List of all users</h1>
<ul class="user-container">
    <%= render partial: 'list', collection: @users, as: :user %>
    <%= button_to 'Log Out', destroy_user_session_path, class: 'out_btn', method: :delete %>
</ul>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Details of <%= myuser.name %></h1>
<%= render partial: 'list', object: myuser, as: :user %>
<div class="bio">
    <h1>Bio</h1>
    <p><%= myuser.bio %></p>
</div>

<h2 style="text-align: center;margin: 5% auto 0 auto;">Recent Posts</h2>
<ul class="posts-container">
    <% posts = myuser.recent_posts(3) %>
    <%= render partial: 'show', collection: posts, as: :post, user: myuser %>
    <div class="buttons">
        <%= button_to 'Add a post', new_user_post_path(myuser.id), method: :get %>
        <%= button_to 'See All posts', user_posts_path(myuser.id), method: :get %>
    </div>
</ul>